[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."save-questions"]
  blobs = ["questions-db"]

[functions."get-questions"]
  blobs = ["questions-db"]