name: Espejo Exacto GitHub a Google Drive

on:
  push:
    branches:
      - main

jobs:
  sync-gdrive:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el codigo de mi repositorio
        uses: actions/checkout@v4

      - name: Subir y Reemplazar Archivos en Google Drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GDRIVE_CREDENTIALS }}
          folderId: ${{ secrets.GDRIVE_FOLDER_ID }}
          filename: 'mossos/**' # Sincroniza la carpeta de mossos completa
          overwrite: "true"
